### ISSUE TITLE
Grid deletes activities permanently and other problems with section moving

### ISSUE THREAD

**Issue by Urpokarhu1** [gjbarnard/moodle-format_grid#117] opened 2020-06-09 07:57 UTC
I have found out that Grid has big problems when you move sections and activities under it. Please see attached video and steps to repeat.

[gridbug.zip](https://github.com/gjb2048/moodle-format_grid/files/4750678/gridbug.zip)

- It renames sections
- adds bulleting points to moved sections 
- deletes activities you try to drag to a moved section completely so they cannot be found from the course recycle bin.

Tested with Moodle 3.5 and format_grid 3.5.0.6 (2018052306)

Steps to repeat:

1. Create a new course and change course format to grid
2. Rename two sections to

- section one
- section two

3. Create page-activity named test to section one.
4. Create new section with the default name section 3
5. Click "move cross"-icon before the section 3 and choose "to item section one"
6. notice how section 3 name changes to "section two" by itself and it gets an bulleting point.
7. Try to move test-activity to under this new section and notice how you cannot do it.
8. Turn editing off in the course
9. Turn editing on in the course
10. Notice how the section name have been changed to "section 2" when it was section 3 
11. Notice that the activity you tried to drag to that section has dissappeared completely and cannot be found in course recycle bin.

**Comment by Urpokarhu1** [comment] 2020-06-09 08:00
@gjb2048

**Comment by gjb2048** [comment] 2020-06-09 10:47
RE: deletes activities you try to drag to a moved section completely so they cannot be found from the course recycle bin.

No it does not!  'test' that was in section one' in the video after drag / drop is now in section 0 at the top in the video.

**Comment by gjb2048** [comment] 2020-06-09 10:50
RE: It renames sections

As per the video and with core course formats, this is the generated name given the order of the sections.  When you actually rename a section then this does not change regardless of where it moves to.  Not a bug!

**Comment by Urpokarhu1** [comment] 2020-06-09 10:53
Hello,

as you can see the name changes when you move the section. Also why is bulleting points added and activities deleted permanentely?

**Comment by gjb2048** [comment] 2020-06-09 10:56
Bullet points are something else.  AND THE ACTIVITIES ARE NOT DELETED PERMANENTLY - READ ABOVE!!!!

**Comment by gjb2048** [comment] 2020-06-09 11:00
Ok bullet points are an oddity of using that specific mechanism (not drag and drop) for moving sections.  Can replicate in Moodle 3.5 but not 3.8.  So inclined for this to be below low priority and probably never fix.

**Comment by Urpokarhu1** [comment] 2020-06-09 11:03
Sorry, it doesn't delete them it moves them to first section. But name section name changes before you take editing mode off.

**Comment by gjb2048** [comment] 2020-06-09 11:05
That's because the JS is renaming them because they have not been set by the user.  This happens in core course formats too.

**Comment by Urpokarhu1** [comment] 2020-06-09 11:06
Ok, that clear it up, thanks for your support.

**Comment by gjb2048** [comment] 2020-06-09 11:10
Move bug when clicking on arrows is an issue in M3.7- versions.  Is complex JS thing.

**Comment by gjb2048** [comment] 2023-09-30 11:41
M3.7- versions no longer supported, closing.

**Closed by gjb2048** 2023-09-30 11:41 UTC
Labels: Bug
