### ISSUE TITLE
The nav-drawer listeners are not set if Theme modifies the layout of the flat navigation list.

### ISSUE THREAD

**Issue by andrewmadden** [gjbarnard/moodle-format_grid#138] opened 2021-05-06 23:59 UTC
As themes can modify the layout of the nav-drawer in many ways, I'm not expecting the code to be able to handle every iteration of what it could be. However, we have a few clients that are using a theme that injects a logo in an anchor element at the start of the list. This means that the first nav element is no longer the first child, however it is still the first nav element.

I propose replacing the selector for the YUI delegate in module.js to get the 'nav:first-of-type' instead of the 'nav:first-child' element to make the code a little more flexible with different themes.

PR incoming.

**Comment by gjb2048** [comment] 2021-05-07 12:30
@andrewmadden Thanks for the information and patch.  Given that the situation is caused by non-core code, therefore will there be financial compensation for the review time I've already spent on this, and then will then need to backport the commit to previous versions?  It is technically an 'enhancement' and I'm now charging for such unless I choose to do so.

**Comment by gjb2048** [comment] 2023-09-30 11:46
Funding not forthcoming, closing.

**Closed by gjb2048** 2023-09-30 11:46 UTC
Labels: Enhancement, Funding required
